[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'

[tool.poetry]
name = "graph-creator"
version = "0.1.0"
description = ""
authors = ["Marius Bause","Thomas Muehlenstaedt"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.15"
jupyter = "^1.1.1"
joblib = "^1.4.2"
shapely = "^2.0.7"
numpy = "2.1"
networkx = "^3.4.2"
matplotlib = "^3.10.1"
pydantic = "^2.10.6"
pandas = "^2.2.3"
seaborn = "^0.13.2"
scipy = "^1.15.2"
tqdm = "^4.67.1"
pyarrow = "^19.0.1"
<<<<<<< HEAD
carla = "^0.9.15"
plotly = "^6.3.0"
=======
>>>>>>> marius/subgraph_extract


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
