[tool.poetry]
name = "carla-scripts"
version = "0.1.0"
description = ""
authors = ["Marius Bause <mariusbause@gmx.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
carla = "^0.9.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
